### ISSUE TITLE
File naming conventions with an underscore

### ISSUE THREAD

**Issue by ablause** [antfu/vscode-file-nesting-config#115]
Hi, I am posting this issue for discussion.
The file naming conventions of some languages are written with an underscore to separate instead of a dot. It would be nice to support this.

Example:
```json
  "*.ts": "$(capture)_test.ts", // for Deno: https://deno.land/manual/contributing/style_guide#use-underscores-not-dashes-in-filenames
  "*.py": "test_$(capture).py",
  "*.rs": "$(capture)_test.rs"
```

> I wonder if we should add only the test files as above or nest all files with an underscore.

**Comment by kidonng** [comment]
Just want to mention this:

> [⚠️ Note that this is the style guide for internal runtime code in the Deno runtime, and in the Deno standard library. This is not meant as a general style guide for users of Deno.](https://deno.land/manual/contributing/style_guide#:~:text=%E2%9A%A0%EF%B8%8F%20Note%20that%20this%20is%20the%20style%20guide%20for%20internal%20runtime%20code%20in%20the%20Deno%20runtime%2C%20and%20in%20the%20Deno%20standard%20library.%20This%20is%20not%20meant%20as%20a%20general%20style%20guide%20for%20users%20of%20Deno.)

**Comment by antfu** [comment]
Close as #119.
