### ISSUE TITLE
Does not support webpack files named like this

### ISSUE THREAD

**Issue by hawtim** [antfu/vscode-file-nesting-config#116]
Hi, I found some kind of webpack files in my project won't be nested

![image](https://user-images.githubusercontent.com/11072796/172121250-50a586c0-f1e7-4620-b75b-ae5e8ffe253f.png)

I am going to raise a PR for this, what do you think.

![image](https://user-images.githubusercontent.com/11072796/172121516-a42c4a3f-af27-4122-9689-b483a6501c07.png)

**Comment by antfu** [comment]
Sure, PR Welcome.

**Comment by hawtim** [comment]
MR raised, help to check with that.
