### ISSUE TITLE
导致文件夹/文件生成多份

### ISSUE THREAD

**Issue by kasodesyn** [antfu/vscode-file-nesting-config#134]
### Describe the bug

![image](https://user-images.githubusercontent.com/112838520/192411925-3fc37be7-9b93-4ae9-b7a4-deb5ef4e18ab.png)

如上图片，很多文件夹和文件，自动被生成了多个，很奇怪。且卸载插件依然存在这个问题。我也在想是不是该插件的问题。

### Reproduction

null

### System Info

```Shell
macos：最新款系统
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kasodesyn** [comment]
![image](https://user-images.githubusercontent.com/112838520/192414638-37757b5f-5126-4d18-a536-6a8717473436.png)

即使卸载插件，功能还会存在

**Comment by antfu** [comment]
This is just how VS Code implements that. This extension is only a config updater.
