### ISSUE TITLE
When I use the VIM plug-in in VS Code at the same time, I can't expand collapsed files in the directory tree via Enter

### ISSUE THREAD

**Issue by zgsgs** [antfu/vscode-file-nesting-config#157]
### Describe the bug

Installed plugins

![image](https://user-images.githubusercontent.com/22882957/233913606-5d877e05-e219-4243-afc3-ff8b1635cb01.png)

![image](https://user-images.githubusercontent.com/22882957/233913673-f55384f5-ce28-4a81-a972-f62f951d3787.png)

The associated file

![image](https://user-images.githubusercontent.com/22882957/233911994-b7550c93-da68-4bb7-ad7a-744d5c2f1107.png)

Select and press Enter
Error message

![image](https://user-images.githubusercontent.com/22882957/233912020-5829c124-47a1-49aa-bfd4-55f9466f9aa3.png)

### Reproduction

This is an application problem, while installing antfu.file-nesting and vscodevim.vim two plug-ins, and select the folded file and press the Enter key to reproduce.

### System Info

```Shell
System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 Intel(R) Core(TM) i7-10700T CPU @ 2.00GHz
    Memory: 16.33 GB / 31.72 GB
  Binaries:
    Node: 16.15.1 - D:\Software\nvm\v16.15.1\node.EXE
    Yarn: 1.22.19 - D:\Software\nvm\v16.15.1\yarn.CMD
    npm: 8.14.0 - D:\Software\nvm\v16.15.1\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.48)
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
This project is just the config, there is nothing we can do about it. Please report upstream.
