### ISSUE TITLE
.nuxtignore under nuxt.config.ts

### ISSUE THREAD

**Issue by adhamfarrag** [antfu/vscode-file-nesting-config#161]
### Clear and concise description of the problem

`.nuxtignore` is rarely needed and for this reason adding it under `nuxt.config.ts` will be nice to have.

### Suggested solution

Can we add `.nuxtignore` under `nuxt.config.ts` ? :) 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sure. PR welcome :)
