### ISSUE TITLE
*.knip.* causing VSCode file explorer does not display files

### ISSUE THREAD

**Issue by level7in** [antfu/vscode-file-nesting-config#186]
### Describe the bug

`*.knip.*` causing the VSCode Explorer does not display files.
> String does not match the pattern of "^([^,*]*\*?[^,*]*)(, ?[^,*]*\*?[^,*]*)*$".
> Each key pattern may contain a single * character which will match any string.

<img width="800" alt="image" src="https://github.com/antfu/vscode-file-nesting-config/assets/9393567/ed749203-dc7b-45da-a10b-a17ecbed33d2">

**Delete `*.knip.*` and it will return to normal.**

<img width="875" alt="image" src="https://github.com/antfu/vscode-file-nesting-config/assets/9393567/2d1d5438-5044-49c3-b048-028ff8f26363">

### Reproduction

Open the folder containing package.json using VSCode.

### System Info

```Shell
Visual Studio Code
Version: 1.85.0 (Universal)
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T18:18:04.614Z (1 day ago)
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 22.6.0  

  System:
    OS: macOS 13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 282.61 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/Library/Caches/fnm_multishells/42942_1702000371659/bin/node
    npm: 10.2.3 - ~/Library/Caches/fnm_multishells/42942_1702000371659/bin/npm
    pnpm: 8.5.0 - ~/Library/pnpm/pnpm
    bun: 1.0.14 - /usr/local/bin/bun
  Browsers:
    Chrome: 120.0.6099.62
    Safari: 17.1
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [ ] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hyrious** [comment]
To make this issue more likely to be found, I'm adding these error messages:

When you open a git repository:

    The file is not displayed in the text editor because it is a directory.

When you open a random folder:

    Unexpected star in SufTrie key: *.knip.*

**Comment by nanvon** [comment]
I have the same problem and same error messages, my system info is:

```
版本: 1.85.0 (system setup)
提交: af28b32d7e553898b2a91af498b1fb666fdebe0c
日期: 2023-12-06T20:48:09.019Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
```
