### ISSUE TITLE
In vscode 1.85.0 version ,  explorer does not display any files and directories

### ISSUE THREAD

**Issue by BryanAdamss** [antfu/vscode-file-nesting-config#188]
### Describe the bug

In the VSCode 1.85.0 version, the explorer does not display any files and directories when "explorer.fileNesting.enabled": true is set. 

![image](https://github.com/antfu/vscode-file-nesting-config/assets/7441504/4fc4f340-7d02-4ae9-b78f-a732bcdecb43)

However, when this setting is changed to "explorer.fileNesting.enabled": false, the files and directories are shown.

![image](https://github.com/antfu/vscode-file-nesting-config/assets/7441504/e964c977-367d-4ac9-9532-75078d11d010)

Is there any rule that affects this behavior?

 vscode version info
```
Version: 1.85.0 (system setup)
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T20:48:09.019Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.18363
```

### Reproduction

In window10 and then download vscode 1.85.0

### System Info

```Shell
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 7.67 GB / 15.74 GB
  Binaries:
    Node: 18.16.0 - ~\AppData\Local\fnm_multishells\16564_1702006014106\node.EXE
    npm: 9.5.1 - ~\AppData\Local\fnm_multishells\16564_1702006014106\npm.CMD
  Browsers:
    Chrome: 120.0.6099.71
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jiechen257** [comment]
> Reason：Unexpected star in SufTrie key: _.knip._
> 
> Temporary workaround： settings.json
> 
> ```json
> "package.json": "*.knip.*, .browserslist*, ..."
> "rush.json": "*.knip.*, .browserslist*, ..."
> // delete *.knip.*,
> "package.json": ".browserslist*, ..."
> "rush.json": ".browserslist*, ..."
> ```

thank u, this works for me

**Comment by BanShan-Alec** [comment]
Same Question. It took me a whole morning to find out what went wrong, even if I reinstalled Vscode. 
Until I look at the "settings.json" change log, I just realized 'vscode-file-nesting-config' is the culprit.

**Comment by antfu** [comment]
It should already be fixed, it might be some network cache issue. You can manually copy the settings from README to override, disable the auto-update, or wait for a while longer until the cache get updated.
