### ISSUE TITLE
Merge `Makefile`

### ISSUE THREAD

**Issue by thoroc** [antfu/vscode-file-nesting-config#195]
### Clear and concise description of the problem

I have several project that uses `Makefile` and associated `*.mk` files. I'd like to make a permanent change so the config updater has those settings.

```json
  "explorer.fileNesting.patterns": {
    "Makefile": "*.mk",
  }
```

### Suggested solution

Add the following to the `update.mjs` file:

```javascript
const base = {
  ...
  'Makefile': '*.mk',
  ...
}
```

### Alternative

Re-adding the pattern matching on every config update.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sure, pr welcome
