### ISSUE TITLE
Publish this extension to JetBrains IDEs

### ISSUE THREAD

**Issue by baruchiro** [antfu/vscode-file-nesting-config#215]
### Clear and concise description of the problem

I was required to move from VSCode to WebStorm, and I don't have the updated nesting configurations there.

### Suggested solution

The file-nesting feature is available on JetBrains too: https://www.jetbrains.com/help/idea/file-nesting-dialog.html

Can we publish this project as a JetBrains plugin?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sorry I don't use JetBrains and have no incentive to work on it. Feel free to fork or port on your own.
