### ISSUE TITLE
`sentry.*.config.*` in `package.json` Breaks explorer view for JS projects

### ISSUE THREAD

**Issue by valtism** [antfu/vscode-file-nesting-config#242]
### Describe the bug

Under `package.json`, the entry `sentry.*.config.*` seems to be breaking everything and removing all files from the explorer

With: 
<img width="276" alt="Screenshot 2024-11-22 at 10 36 16 am" src="https://github.com/user-attachments/assets/8b8f2eb0-c7cd-46d8-be45-16c893791b19">

Without: 
<img width="284" alt="Screenshot 2024-11-22 at 10 36 20 am" src="https://github.com/user-attachments/assets/b10e3809-8c80-45bb-9652-88a5e134563f">

### Reproduction

create a new project with `npm create vite@latest` and the latest config and you should see it

### System Info

```Shell
System:
    OS: macOS 15.1
    CPU: (10) arm64 Apple M4
    Memory: 2.45 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.local/share/mise/installs/node/20.11.0/bin/node
    npm: 10.2.4 - ~/.local/share/mise/installs/node/20.11.0/bin/npm
  Browsers:
    Chrome: 131.0.6778.86
    Safari: 18.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [x] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by roojay520** [comment]
The same issue causes the entire folder to not display.

**Comment by yanhao98** [comment]
+1

<img width="1408" alt="image" src="https://github.com/user-attachments/assets/86700e01-c463-4aed-b32c-98cb3e4b08a9">

**Comment by xiangshu233** [comment]
是最新的一次提交到的 #240 ，昨天下班前还好好的，今天早上上班突然不行了，我重启 重装 清缓存都试了，从来没怀疑这个插件，我真的裂开，我都去看 vscode 文档了，浪费了我整整一个上午时间
我不明白
为什么这个提交会在没有测试情况下被合并

**Comment by xiangshu233** [comment]
是最新的一次提交导致的 #240，昨天下班前还好好的，今天早上上班突然不行了，我重启 重装 清缓存都试了，从来没怀疑这个插件，我真的裂开，我都去看 vscode 文档了，浪费了我整整一个上午时间
我不明白
为什么这个提交会在没有测试情况下被合并

**Comment by VdustR** [comment]
Similar to this
https://github.com/antfu/vscode-file-nesting-config/issues/186

**Comment by Gugustinette** [comment]
Had the issue this morning, do not forget to use the `> File Nesting Updater: Update config now` vscode command to fix 👍

**Comment by chetan** [comment]
Looks like it fetches the updates via an external CDN and so it may take time to propagate everywhere. For now a manual fix should get things working again.
