### ISSUE TITLE
最新的 commit 出现无法打开项目目录的 bug ！！！

### ISSUE THREAD

**Issue by xiangshu233** [antfu/vscode-file-nesting-config#244]
### Describe the bug

昨天下班前还是正常的，今天开机一开电脑整个项目都打不开了，换其他项目也不行，重启清理缓存都不行，把所有插件都卸载（File Nesting Updater 的配置 还在 setting.json 中）整整搞了一上午都没找到问题所在，最后卸载重装全部一个一个 删除 `setting.json` 的内容 才知道这个插件最近一次更新导致的，这也太搞人心态了

打开仓库一看 18小时前有提交 #240   这个提交为什么会在没有测试的情况下自动合并了，我裂开。。。

https://github.com/user-attachments/assets/93bb5435-5c0b-49b2-aaa9-0262b90af03e

### Reproduction

https://github.com/user-attachments/assets/93bb5435-5c0b-49b2-aaa9-0262b90af03e

### System Info

```Shell
与系统无关
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by roiiiu** [comment]
同样遇到

**Comment by xiangshu233** [comment]
@roiiiu 我卸载了，真的太搞心态了，整整一上午啥也没干就在排查这个问题

**Comment by vvizden** [comment]
> @roiiiu 我卸载了，真的太搞心态了，整整一上午啥也没干就在排查这个问题

也是排查了一上午，去 settings.json 中将 `explorer.fileNesting.*` 相关的配置删掉就好了，等配置更新吧😂

**Comment by saltbo** [comment]
心态崩了

**Comment by moeyua** [comment]
可以先删 setting.json 中的所有 `sentry.*.config.*`

**Comment by ilyaliao** [comment]
我想最新的提交已經解決，目前測試沒問題
