### ISSUE TITLE
The config assumes case insensitivity

### ISSUE THREAD

**Issue by aminya** [antfu/vscode-file-nesting-config#42]
I don't know if this is a system-specific bug, but unless I exactly follow the case of the files, they are not activated.

**Comment by antfu** [comment]
I am not sure if it's a bug of VS Code, if I put uppercase in the pattern it won't work. I am using a case insensitivity system so I can really test it. Please feel free to modifify the config and see what works for you, and maybe send a PR over. Thanks.

**Comment by aminya** [comment]
I tested two systems. On Windows, it requires lower case config, but on Linux (WSL), the config should match the case.

**Comment by dzhavat** [comment]
It is a bug https://github.com/microsoft/vscode/issues/142390

From my testing on Windows, it looks like lower case patterns will match mixed case files, but not the other way around.

**Comment by aminya** [comment]
I am using the latest VsCode insiders and the bug still exists. I think it is better to support both cases. It should be very easy to automate that. We can have one actual case (e.g. TitleCase, Readme), and one lowercase (e.g. lowercase, readme)
