### ISSUE TITLE
Take `tsx` children files in consideration

### ISSUE THREAD

**Issue by RPDeshaies** [antfu/vscode-file-nesting-config#70]
Hi! 

I love your config, but I was wondering if it was intentional to ignore `$(capture).*.tsx` in the `*.tsx` rule ?
Because, with this config, spec files like `MyFile.test.tsx` would become a child of `MyFile.tsx`.

I'm asking because this rule is present for `ts` files.

```
    "*.ts": "$(capture).js, $(capture).*.ts",
    "*.tsx": "$(capture).ts",
```

VS

```
    "*.ts": "$(capture).js, $(capture).*.ts",
    "*.tsx": "$(capture).ts, $(capture).*.tsx",
```

Thanks

**Comment by antfu** [comment]
They were copied from the example of VS Code's release note. PR welcome.

**Comment by RPDeshaies** [comment]
PR opened!

https://github.com/antfu/vscode-file-nesting-config/pull/72
