### ISSUE TITLE
文件重复显示

### ISSUE THREAD

**Issue by CodeDreamfy** [antfu/vscode-file-nesting-config#74]
### Expected behaviour
当某个文件被收纳到某个文件之下时候，只会被匹配一次

### Actual behaviour
在`vue`项目中，一些文件会被重复归纳到一些文件下面，如下图：
![](https://s1.ax1x.com/2022/03/16/qSyPXt.png)

### I'm seeing this behaviour on
- [x] Mac 10.15.7
- [x] vscode 1.65.2
- [x] vue-cli3

**Comment by antfu** [comment]
Yes, sadly this is how VS Code behaves currently. I would expect them to provide a better interface in the future.
