### ISSUE TITLE
Nest test files (JS/TS)

### ISSUE THREAD

**Issue by baruchiro** [antfu/vscode-file-nesting-config#81]
There is a convention in JS/TS to name the test file with `$(capture).test.js`, like this:

![image](https://user-images.githubusercontent.com/17686879/159163723-9d4f6b7c-d946-4711-83bc-1aef64e306ee.png)

Do you think we can nest those test files under the main file?

**Comment by antfu** [comment]
Sure. I believe also *.spec.js. PR welcome
