### ISSUE TITLE
Consider downloading config from other's repo to make it more shareable?

### ISSUE THREAD

**Issue by sqrthree** [antfu/vscode-file-nesting-config#82]
Thank you for the extension, it's really useful. But as you say, the snippet is opinionated. If the variable [URL](https://github.com/antfu/vscode-file-nesting-config/blob/c4ca67484f/extension/src/constants.ts#L1) can be configured in VS Code configurations, users can then update from any favorite repo. I think it will be more shareable. 😀

**Comment by antfu** [comment]
PR welcome

**Comment by Shinigami92** [comment]
So we may need to move the content to a real json file, and after that we could link with a configurable URL to any gist :eyes: 
That could really be useful, could it?

We could even create some presets :thinking:

**Comment by antfu** [comment]
Actually, the ideal method in my mind is we move the generation logic directly to the extension, and provide a more human-friendly API to configure those entries so ppl could customize the generation as they want.

That could use quite some effort, considering the current solution works well, and VS Code might improve the config interface in the future, I personally do not have enough motivation to push it right now. So PR welcome again (or take this idea and create a new project).
