### ISSUE TITLE
fileNesting is no longer experimental under insider version

### ISSUE THREAD

**Issue by ctf0** [antfu/vscode-file-nesting-config#85]
```
Version: 1.66.0-insider
Commit: eaa2b431ac259fddf5aa11aa53060a9b70068b29
Date: 2022-03-21T07:22:12.653Z
Electron: 17.1.2
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.4.
```

<img width="1043" alt="Screen Shot 2022-03-22 at 10 28 54 AM" src="https://user-images.githubusercontent.com/7388088/159439039-034d3f3d-216f-4a90-95aa-5a307bda5d92.png">

so is it possible to check for that b4 updating the config ?

**Comment by ctf0** [comment]
apprently its back as experimental again, fock 🤦‍♂️

**Comment by antfu** [comment]
I will close it for now. We will act on it when it comes to stable releases.
