### ISSUE TITLE
File state synchronization problem in workspace

### ISSUE THREAD

**Issue by xlboy** [antfu/vscode-file-nesting-config#87]
--------------**VSCode**--------------
Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:42:05.236Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0

--------------**PluginExtension**--------------
Version: 0.1.1

--------------**Issue**--------------
When in workspace mode, when the configuration file of workspace 1 is moved to workspace 2, it will not be synchronized in real time. 

![Example](https://user-images.githubusercontent.com/63690944/159667787-7fcb2c0f-6fdc-40b3-9729-85009dc80e83.GIF)

**Comment by antfu** [comment]
It's a bug of VS Code. This repo is only about the config.
