### ISSUE TITLE
jsconfig.json repeat

### ISSUE THREAD

**Issue by BanShan-Alec** [antfu/vscode-file-nesting-config#94]
![Snipaste_2022-04-11_08-57-06](https://user-images.githubusercontent.com/44499686/162648564-f78083bf-25d7-43e2-ac18-7e0d5a70e606.png)

**Comment by leonardssh** [comment]
Same issue for `tsconfig.json`

![image](https://user-images.githubusercontent.com/35312043/166112805-7ecaa4c6-6b38-4e0a-92ac-538b5372a286.png)
