### ISSUE TITLE
Use onStartupFinished to replace * in activationEvents

### ISSUE THREAD

**Issue by frg2089** [antfu/vscode-file-nesting-config#97]
see document [Activation Events | Visual Studio Code Extension API](https://code.visualstudio.com/api/references/activation-events#onStartupFinished)
> ## [onStartupFinished](https://code.visualstudio.com/api/references/activation-events#onStartupFinished)
> This activation event is emitted and interested extensions will be activated **some time after** VS Code starts up. This is similar to the `*` activation event, but it will not slow down VS Code startup. Currently, this event is emitted after all the `*` activated extensions have finished activating.
> ```json
> ...
> "activationEvents": [
>     "onStartupFinished"
> ]
> ...
> ```

https://github.com/antfu/vscode-file-nesting-config/blob/93659d4882476d73019a6036e8e6c68afa90e072/extension/package.json#L59-L61

**Comment by antfu** [comment]
PR welcome!
